import Head from 'next/head'
import {useQuery} from "urql";
import {PRODUCT_QUERY} from "../lib/query";
import Product from '@/components/Products';
import { Gallery } from '@/styles/Gallery';
import { NumerologyComponent } from '@/components/Numerology';
import { ReportComponent } from '@/components/Report';

export default function Home() {

  //Fetch strapi
  // const [results] = useQuery({query: PRODUCT_QUERY});
  // const {data, fetching, error} = results;
  // if(fetching) return <p>Loading...</p>
  // if(error) return <p>Oh nooo {error.message}</p>
  // const products = data.products.data;


  return (
    <>
      <Head>
        <title>TSH 3 Gốc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
        {/* <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" />
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script> */}
      </Head>
      <main>
        {/* <NumerologyComponent /> */}
        <ReportComponent />
        {/* <Gallery>
          {products.map((product) => 
            <Product key={product.attributes.slug} product={product}/>
          )}
        </Gallery> */}
      </main>
    </>
  )
}
